### ISSUE TITLE
[bug] Game do not restart after snake hit the body

### ISSUE THREAD

**Issue by Alex-Lin5** [Subh0m0y/Snake#1]
Generally, the game should be able to restart pressing 'enter' key. If you press any key other than it, the game will not restart and the program is dead.

**Comment by Subh0m0y** [comment]
Fork it and consider contributing! That's why the repository is public!

Also, I'm not really interested in Java anymore. I am a developer for the V
programming language now. I won't be making any contributions to my old
projects unless I'm compensated.

**Comment by Alex-Lin5** [comment]
Yeah, I am taking a class of object-oriented design. I am considering to contribute your program.

**Comment by Alex-Lin5** [comment]
It is fixed. Consider accept my pull request!
